import { Prompt, PromptType, Category } from './types';

// Using numeric IDs to match Category interface
export const CATEGORIES: Category[] = [
  { id: 0, name: 'All Prompts', slug: 'all', description: 'All prompts' },
  { id: -1, name: 'My Favorites', slug: 'favorites', description: 'My Favorites', color: 'bg-amber-100 text-amber-800' },
  { id: 1, name: 'Academic', slug: 'academic', description: 'Academic', color: 'bg-blue-100 text-blue-800' },
  { id: 2, name: 'Business Strategy', slug: 'business', description: 'Business Strategy', color: 'bg-emerald-100 text-emerald-800' },
  { id: 3, name: 'Web Development', slug: 'coding', description: 'Web Development', color: 'bg-slate-100 text-slate-800' },
  { id: 4, name: 'Creative Writing', slug: 'creative', description: 'Creative Writing', color: 'bg-purple-100 text-purple-800' },
  { id: 5, name: 'Image Gen', slug: 'image', description: 'Image Gen', color: 'bg-pink-100 text-pink-800' },
  { id: 6, name: 'Medical/Health', slug: 'health', description: 'Medical/Health', color: 'bg-red-100 text-red-800' },
];

const DEFAULT_DATE = new Date().toISOString();

export const MOCK_PROMPTS: Prompt[] = [
  {
    id: 1,
    title: '$500/Hour AI Consultant',
    description: 'Act as a high-level business consultant to solve complex organizational problems with strategic frameworks.',
    prompt_text: 'Act as a top-tier management consultant (McKinsey/Bain style). I will present a business problem, and you will break it down using MECE frameworks, conduct a root cause analysis, and propose 3 strategic solutions with ROI estimates.',
    author_name: 'BizGuru',
    author_id: 101,
    tags: ['Consulting', 'Business', 'Strategy', 'High Value'],
    category_id: 2,
    prompt_type: PromptType.TEXT,
    view_count: 1240,
    is_featured: true,
    is_published: true,
    copy_count: 0,
    created_at: DEFAULT_DATE,
    updated_at: DEFAULT_DATE,
    language: 'en'
  },
  {
    id: 2,
    title: 'Cyberpunk I-Ching Divination',
    description: 'A creative app-like experience that interprets ancient I-Ching hexagrams through a neon-soaked cyberpunk lens.',
    prompt_text: 'You are a glitched AI oracle from the year 2099. When I ask a question, cast an I-Ching hexagram. Interpret the result not in traditional terms, but using cyberpunk metaphors (corporations, netrunning, augmentation, decay). Be cryptic but insightful.',
    author_name: 'NeoVibe',
    author_id: 102,
    tags: ['Creative', 'Game', 'Roleplay', 'Sci-Fi'],
    category_id: 4,
    prompt_type: PromptType.TEXT,
    view_count: 850,
    is_featured: false,
    is_published: true,
    copy_count: 0,
    created_at: DEFAULT_DATE,
    updated_at: DEFAULT_DATE,
    language: 'en'
  },
  {
    id: 3,
    title: 'Midjourney: 90s Movie Scene',
    description: 'Generate hyper-realistic film stills looking like a 1990s blockbuster thriller.',
    prompt_text: '/imagine prompt: cinematic film still, 1990s thriller movie, grain, bokeh, suspenseful atmosphere, low key lighting, 35mm film stock --ar 16:9 --v 6.0',
    author_name: 'VisualArt',
    author_id: 103,
    tags: ['Midjourney', 'Photography', 'Cinema', 'Retro'],
    category_id: 5,
    prompt_type: PromptType.IMAGE,
    view_count: 2100,
    is_featured: true,
    is_published: true,
    copy_count: 0,
    created_at: DEFAULT_DATE,
    updated_at: DEFAULT_DATE,
    language: 'en'
  },
  {
    id: 4,
    title: 'Kognitiv Aktivierende Aufgaben',
    description: 'Create engaging, cognitively activating tasks for students based on a specific topic.',
    prompt_text: 'Act as a pedagogical expert. Create 3 "cognitively activating" tasks (kognitiv aktivierende Aufgaben) for a 10th-grade history class on the topic of [TOPIC]. Ensure they require critical thinking, not just recall.',
    author_name: 'EduPro_DE',
    author_id: 104,
    tags: ['Education', 'German', 'Teaching', 'Lesson Planning'],
    category_id: 1,
    prompt_type: PromptType.TEXT,
    view_count: 430,
    is_featured: false,
    is_published: true,
    copy_count: 0,
    created_at: DEFAULT_DATE,
    updated_at: DEFAULT_DATE,
    language: 'de'
  },
  {
    id: 5,
    title: 'React & Tailwind Component Gen',
    description: 'Expert frontend engineer prompt for generating clean, responsive UI components.',
    prompt_text: 'Act as a senior React engineer. Create a [COMPONENT NAME] using React, TypeScript, and Tailwind CSS. Ensure accessibility (ARIA), responsive design, and clean code structure. Do not use external CSS files.',
    author_name: 'DevMaster',
    author_id: 105,
    tags: ['Coding', 'React', 'Frontend', 'Web Dev'],
    category_id: 3,
    prompt_type: PromptType.CODE,
    view_count: 3500,
    is_featured: true,
    is_published: true,
    copy_count: 0,
    created_at: DEFAULT_DATE,
    updated_at: DEFAULT_DATE,
    language: 'en'
  },
  {
    id: 6,
    title: 'AI Agent Security Checklist',
    description: 'A comprehensive security audit list for deploying autonomous AI agents in enterprise environments.',
    prompt_text: 'Generate a security checklist for an autonomous AI agent deployment. Cover: Prompt Injection, Data Leakage, Excessive Permissions, and Hallucination handling. Output as a markdown table with Risk Level and Mitigation Strategy.',
    author_name: 'SecOps',
    author_id: 106,
    tags: ['Security', 'AI Safety', 'Enterprise', 'Checklist'],
    category_id: 3,
    prompt_type: PromptType.TEXT,
    view_count: 670,
    is_featured: false,
    is_published: true,
    copy_count: 0,
    created_at: DEFAULT_DATE,
    updated_at: DEFAULT_DATE,
    language: 'en'
  },
  {
    id: 7,
    title: 'WorldQuant Alpha Optimization',
    description: 'Technical prompt for quantitative finance researchers to optimize alpha signals.',
    prompt_text: 'Act as a quantitative researcher at WorldQuant. Review the following alpha signal expression. Suggest optimizations to improve the Sharpe ratio and reduce turnover. Explain the mathematical intuition.',
    author_name: 'QuantKing',
    author_id: 107,
    tags: ['Finance', 'Math', 'Data Analysis', 'Complex'],
    category_id: 1,
    prompt_type: PromptType.TEXT,
    view_count: 220,
    is_featured: false,
    is_published: true,
    copy_count: 0,
    created_at: DEFAULT_DATE,
    updated_at: DEFAULT_DATE,
    language: 'en'
  },
  {
    id: 8,
    title: 'HR Compensation Design',
    description: 'Design a fair and competitive compensation package based on KPIs and market data.',
    prompt_text: 'Act as an HR Compensation Specialist. Design a compensation package for a [ROLE] in [LOCATION]. Include base salary, variable performance bonus (linked to specific KPIs), and equity. Justify numbers with current market trends.',
    author_name: 'PeopleOps',
    author_id: 108,
    tags: ['HR', 'Management', 'Corporate', 'Finance'],
    category_id: 2,
    prompt_type: PromptType.TEXT,
    view_count: 310,
    is_featured: false,
    is_published: true,
    copy_count: 0,
    created_at: DEFAULT_DATE,
    updated_at: DEFAULT_DATE,
    language: 'en'
  },
  {
    id: 9,
    title: 'Virtual Doctor: Symptom Checker',
    description: 'A triage assistant prompt (for educational purposes only) to simulate patient intake.',
    prompt_text: 'Act as a sympathetic triage nurse. I will list symptoms. You will ask clarifying questions (one by one) to rule out emergencies (Red Flags). Finally, summarize the likely condition categories. Disclaimer: State clearly this is not medical advice.',
    author_name: 'MedTech',
    author_id: 109,
    tags: ['Medical', 'Health', 'Roleplay', 'Triage'],
    category_id: 6,
    prompt_type: PromptType.TEXT,
    view_count: 550,
    is_featured: false,
    is_published: true,
    copy_count: 0,
    created_at: DEFAULT_DATE,
    updated_at: DEFAULT_DATE,
    language: 'en'
  },
  {
    id: 10,
    title: 'DALL-E 3: Surrealist Portraits',
    description: 'Create melting, dreamlike portraits in the style of Salvador Dali meets Cyberpunk.',
    prompt_text: 'Oil painting of a cyborg face melting into a digital clock, surrealist style, Salvador Dali influence, neon palette, dreamlike atmosphere, high detail.',
    author_name: 'ArtBot',
    author_id: 110,
    tags: ['DALL-E', 'Art', 'Surrealism', 'Creative'],
    category_id: 5,
    prompt_type: PromptType.IMAGE,
    view_count: 1100,
    is_featured: false,
    is_published: true,
    copy_count: 0,
    created_at: DEFAULT_DATE,
    updated_at: DEFAULT_DATE,
    language: 'en'
  }
];